[tool.poetry.dependencies]
gunicorn = "^20.1.0"
[tool.poetry]
name = "fair_assess1"
version = "0.1.0"
description = "A short description of your project"
authors = ["Your Name <your.email@example.com>"]
